Results will be saved in results/world_trade_1995_20240805142227
Command line input: python seal_link_pred.py --dataset world_trade_1995 --fast_split --num_hops 1 --use_feature --eval_steps 1 --runs 3 --epochs 10 --dynamic_train --dynamic_val --dynamic_test --train_percent 2 --val_percent 1 --test_percent 1 --use_dl
 is saved.
Data found, skipping download...
Path /grphome/grp_supplychainai/nobackup/archive/world_trade_seal_h1_drnl_rph10
num nodes 238
Total number of parameters is 73538
SortPooling k is set to 25
  0%|                                           | 0/1 [00:00<?, ?it/s]  0%|                                           | 0/1 [00:01<?, ?it/s]
z torch.Size([801, 32])
first x torch.Size([801, 4])
x torch.Size([801, 36])
dl torch.Size([801, 32])
Traceback (most recent call last):
  File "seal_link_pred.py", line 1329, in <module>
    loss = train()
  File "seal_link_pred.py", line 519, in train
    logits = model(data.z, data.edge_index, data.batch, dl, x, edge_weight, node_id)
  File "/grphome/grp_supplychainai/.conda/envs/sealenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/grphome/grp_supplychainai/.conda/envs/sealenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/grphome/grp_supplychainai/SEAL_OGB/models.py", line 245, in forward
    x = torch.cat([dl_emb, x], 0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 32 but got size 36 for tensor number 1 in the list.
